# Generated by Django 3.1.3 on 2020-12-30 04:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Backlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=255)),
                ('model_name', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.IntegerField(choices=[(1, 'Urls'), (2, 'Views'), (3, 'Models'), (4, 'Templates'), (5, 'Static'), (6, 'Admin'), (7, 'Forms'), (8, 'Media'), (9, 'Settings'), (10, 'Signals'), (11, 'Converters'), (12, 'Custom Tags'), (13, 'Tests'), (99, 'Other')], verbose_name='categories')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('priority', models.IntegerField(choices=[(1, 'High'), (2, 'Medium'), (3, 'Low'), (4, 'Horizon')], default=2, verbose_name='priorities')),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Completed'), (3, 'Wont Fix')], default=1, verbose_name='statuses')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backlog_items_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backlog_items_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
