# Generated by Django 3.1.3 on 2020-11-03 02:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0002_auto_20201102_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='user_likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='liked_products', to=settings.AUTH_USER_MODEL),
        ),
    ]
