# Generated by Django 3.1.3 on 2020-11-04 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_product_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='date_answered',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='date_asked',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
