# Generated by Django 3.1.3 on 2020-11-15 18:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20201115_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='date_answered',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2020, 11, 15, 13, 59, 32, 379016)),
            preserve_default=False,
        ),
    ]
