# Generated by Django 3.1.3 on 2020-11-15 21:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20201115_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created',
            field=models.DateField(default=datetime.datetime(2020, 11, 15, 21, 7, 26, 726254, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='category',
            name='update',
            field=models.DateField(default=datetime.datetime(2020, 11, 15, 21, 7, 26, 726254, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2020, 11, 15, 21, 7, 26, 726254, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateField(default=datetime.datetime(2020, 11, 15, 21, 7, 26, 726254, tzinfo=utc)),
        ),
    ]
