# Generated by Django 3.1.3 on 2020-11-15 21:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20201115_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 15, 21, 13, 6, 513500, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2020, 11, 15, 21, 13, 6, 513500, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='category',
            name='update',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 15, 21, 13, 6, 513500, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateField(default=datetime.datetime(2020, 11, 15, 21, 13, 6, 513500, tzinfo=utc)),
        ),
    ]
