# Generated by Django 3.1.3 on 2020-11-15 21:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_auto_20201115_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 15, 21, 31, 18, 42033, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='category',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 15, 21, 31, 18, 42033, tzinfo=utc)),
        ),
    ]
