# Generated by Django 3.1.3 on 2020-12-08 01:05

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_product_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size_chart',
            field=models.FileField(blank=True, null=True, upload_to=shop.models.product_directory_path),
        ),
    ]
