# Generated by Django 3.1.3 on 2020-12-08 02:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_promotions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotions',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
