# Generated by Django 3.1.3 on 2020-12-26 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0035_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='sale',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='shop.sale'),
            preserve_default=False,
        ),
    ]
