# Generated by Django 3.1.3 on 2020-12-28 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0037_auto_20201226_0510'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favorites',
            field=models.ManyToManyField(blank=True, null=True, related_name='favorited_by', to='shop.Product'),
        ),
    ]
