# Generated by Django 3.1.3 on 2021-01-20 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0040_auto_20210119_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='promo_code',
            field=models.CharField(blank=True, help_text='Try to keep the code short (under 10 characters).', max_length=20, null=True),
        ),
    ]
