# Generated by Django 3.1.3 on 2021-01-21 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0041_sale_promo_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='review',
            field=models.CharField(blank=True, help_text="Let other shoppers know what you liked, or didn't, about this purchase.", max_length=255, null=True),
        ),
    ]
