# Generated by Django 3.1.3 on 2021-11-26 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0042_auto_20210120_2307'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['name'], 'verbose_name_plural': 'collections'},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-start_date'], 'verbose_name_plural': 'sales'},
        ),
    ]
