# Generated by Django 3.1.3 on 2021-11-26 17:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0043_auto_20211126_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='followers',
            field=models.ManyToManyField(blank=True, null=True, related_name='questions_followed', to=settings.AUTH_USER_MODEL),
        ),
    ]
