# Generated by Django 3.1.3 on 2020-12-06 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20201205_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.IntegerField(choices=[(1, 'Open'), (2, 'Pending'), (3, 'Completed')], default=1),
        ),
    ]
