# Generated by Django 3.1.3 on 2021-12-05 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_auto_20201207_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.IntegerField(choices=[(1, 'Open'), (2, 'Pending'), (3, 'Completed'), (4, 'Expired')], default=1),
        ),
    ]
