# Generated by Django 3.1.3 on 2021-12-05 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_auto_20211205_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='is_taxable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='tax_rate',
            field=models.DecimalField(blank=True, decimal_places=10, default=0.0, max_digits=12, null=True),
        ),
    ]
